---
title: "Set-up"
authors:
  - name: Amy Heather
    url: https://github.com/amyheather
    orcid: 0000-0002-6596-3479
    affiliation: Peninsula Collaboration for Health Operational Research and Data Science (PenCHORD), University of Exeter Medical School
---

There are two important set-up steps for `pywebexercises`:

* Installing the `.js` and `.css` files
* Including the files in the front matter of our `.qmd file`.

<br>

## Installing the `.js` and `.css` files

The `pywebexercises` package contains functions which will generate `html`. This html is processed by two scripts:

* `webex.js`
* `webex.css`

Which convert the html into interactive questions for users to answer.

A function is provided to install these files into your current directory into an `assets/` folder.

```{.python}
# pylint: disable=missing-module-docstring
from pywebexercises.setup import setup_webex_assets

setup_webex_assets()
```

### Alternatively...

These files can also be copied from below:

:::{.callout-note collapse="true"}

## webex.js

```{.js}
{{< include ../../src/pywebexercises/assets/webex.js >}}
```

:::

:::{.callout-note collapse="true"}

## webex.css

```{.css}
{{< include ../../src/pywebexercises/assets/webex.css >}}
```

:::

<br>

## Front matter

To render our exercises in our quarto site, we first need to include the following in the front matter of our `.qmd` file:

```
format: 
  html:
    css: [assets/webex.css]
    include-after-body: [assets/webex.js]
    embed-resources: true 
```

The path to the files may be `assets/...`, or changed to an appropriate path for your project.
