project:
  type: website
  preview:
    browser: true

website:
  title: "pywebexercises"
  navbar:
    search: true
    left:
      - index.qmd
      - pages/exercises.qmd
    tools:
      - icon: github
        href: https://github.com/amyheather/pywebexercises