name: pywebexercises
channels:
  - conda-forge
dependencies:
  - ipykernel=6.29.5
  - nbclient=0.10.2
  - nbformat=5.10.4
  - nbqa=1.9.0
  - python=3.13.1
  - pip=25.0.1
  - pylint=3.3.4
  - pytest=8.3.4
  - pyyaml==6.0.2
  - pip:
    - -e .[dev]