---
title: "Exercises"
authors:
  - name: Amy Heather
    url: https://github.com/amyheather
    orcid: 0000-0002-6596-3479
    affiliation: Peninsula Collaboration for Health Operational Research and Data Science (PenCHORD), University of Exeter Medical School
format: 
  html:
    css: [../pywebexercises/assets/webex.css]
    include-after-body: [../pywebexercises/assets/webex.js]
    embed-resources: true 
---

This page demonstrates the functionality available in `pywebexercises`:

* Multiple choice questions (MCQs).
* Long MCQs.
* True or false questions.
* Checked sections.

First, you need to have followed the set-up instructions in the **"Setup"** page.

Then, import the exercise functions we are going to use...

```{python}
# pylint: disable=missing-module-docstring
from pywebexercises.exercises import mcq, longmcq, torf
```

<br>

**Important:** When using these functions, set `#| echo: false` to prevent the code from showing in your document.

<br>

## MCQ

The `mcq()` function will produce a drop-down box.

:::{.callout-note}

## How many legs does a spider have?

```{python}
#| echo: false
mcq({
    '1': 0,
    '3': 0,
    '8': 1,
    '200': 0
})
```

:::

This was generated by running:

```{python}
#| eval: false
mcq({
    '1': 0,
    '3': 0,
    '8': 1,
    '200': 0
})
```

<br>

## LongMCQ

The `longmcq()` function will produce radio buttons.

:::{.callout-note}

## How many legs does a spider have?

```{python}
#| echo: false
longmcq({
    '1': 0,
    '3': 0,
    '8': 1,
    '200': 0
})
```

:::

This was generated by running:

```{python}
#| eval: false
longmcq({
    '1': 0,
    '3': 0,
    '8': 1,
    '200': 0
})
```

<br>

## True or false

The `torf()` function can be used to create a drop-down with options of True or False.

:::{.callout-note}

## We live on the planet Mars.

```{python}
#| echo: false
torf(False)
```

:::

That was generated by running:

```{python}
#| eval: false
torf(False)
```

<br>

## Checked sections

These are created by making a `webex-check` section, which will add a button that will only display feedback when pressed.

You can also include `.webex-box` to draw a box around the section.

```
:::{.webex-check .webex-box}

# Question/s here

:::
```

For example...

<br>

### Using `webex-check` and `webex-box`

:::{.webex-check .webex-box}

What is a baby dog called?

```{python}
#| echo: false
longmcq({
    'kitten': 0,
    'puppy': 1
})
```

What is a baby sheep called?

```{python}
#| echo: false
longmcq({
    'lamb': 1,
    'calf': 0
})
```

:::

<br>

### Just using `webex-check`

:::{.webex-check}

What is a baby dog called?

```{python}
#| echo: false
longmcq({
    'kitten': 0,
    'puppy': 1
})
```

What is a baby sheep called?

```{python}
#| echo: false
longmcq({
    'lamb': 1,
    'calf': 0
})
```

:::

<br>

### Just using `webex-box`

:::{.webex-box}

What is a baby dog called?

```{python}
#| echo: false
longmcq({
    'kitten': 0,
    'puppy': 1
})
```

:::